version: '3'

services:
  db:
    image: mysql:5.7
    # volumes:
    #   - ./db_data/:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tm_db
      MYSQL_USER: task
      MYSQL_PASSWORD: pass
    ports:
      - "9906:3306"
    networks:
      - tm_lamp

  web:
    image: richarvey/nginx-php-fpm:latest
    restart: always
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    networks:
      - tm_lamp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    external_links:
      - db:mysql
    ports:
      - "8081:80"
    environment:
      MYSQL_USER: task
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      PMA_HOST: db
    networks:
      - tm_lamp

networks:
  tm_lamp:
# volumes:
#   db_data: